# Generated by Django 5.1.4 on 2025-11-11 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registered_Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('university', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('t_shirt_size', models.CharField(blank=True, max_length=20, null=True)),
                ('unique_code', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Registered Participant',
            },
        ),
        migrations.CreateModel(
            name='Token_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('order_of_session', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Token Session',
            },
        ),
        migrations.CreateModel(
            name='Token_Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('registered_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registered_participant')),
                ('token_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.token_session')),
            ],
            options={
                'verbose_name': 'Applied Participant Token',
            },
        ),
    ]
