# Generated by Django 5.1.4 on 2025-11-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Form Status',
            },
        ),
        migrations.CreateModel(
            name='Form_Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('is_nsu_student', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nsu_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('university', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('university_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('major', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('membership_type', models.CharField(choices=[('member', 'IEEE Member'), ('non_ieee', 'Non-IEEE Member')], max_length=20)),
                ('ieee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('ambassador_code', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('joining_as', models.CharField(choices=[('participant', 'Participant'), ('participant_pstpre_contestant', 'Participant and Poster Presentation Contestant'), ('participant_pwrolmp_contestant', 'Participant and Power Olympiad Contestant')], default='participant', max_length=35)),
                ('registering_for_team', models.BooleanField(default=False)),
                ('team_member_count', models.CharField(blank=True, max_length=5, null=True)),
                ('team_mem_1_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team_mem_1_university', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('team_mem_1_university_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('team_mem_2_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team_mem_2_university', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('team_mem_2_university_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('Bkash', 'Bkash')], default='Bkash', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form Participant',
            },
        ),
    ]
