# Generated by Django 5.1.4 on 2025-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_participant',
            name='team_mem_1_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='form_participant',
            name='team_mem_2_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
