# Generated by Django 5.1.4 on 2025-11-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_form_participant_team_mem_1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_participant',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
