# Generated by Django 5.1.4 on 2025-11-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_form_participant_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_participant',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=5, null=True),
        ),
    ]
