# Generated by Django 5.1.4 on 2025-12-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_form_participant_tshirt_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Participant_Phase_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('membership_type', models.CharField(choices=[('non_ieee', 'Non IEEE Member'), ('member', 'IEEE Member')], default='non_ieee', max_length=10)),
                ('is_nsu_student', models.BooleanField(default=False)),
                ('ieee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('university', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('university_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ambassador_code', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('answers', models.JSONField(default=dict)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant Form (Phase 1)',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'University',
            },
        ),
        migrations.DeleteModel(
            name='Form_Participant',
        ),
    ]
