# Generated by Django 5.1.4 on 2025-12-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_form_participant_phase_1_university_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Participant_Unique_Code_Phase_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=50)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.form_participant_phase_1')),
            ],
            options={
                'verbose_name': 'Unique Code for Phase 2',
            },
        ),
    ]
