# Generated by Django 5.1.4 on 2025-12-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_form_participant_unique_code_phase_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_participant_phase_1',
            name='is_phase_2_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form_participant_phase_1',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
