# Generated by Django 5.1.4 on 2025-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_form_participant_phase_1_is_phase_2_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_participant_unique_code_phase_2',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
