# Generated by Django 5.1.4 on 2025-12-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_form_participant_unique_code_phase_2_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_participant_unique_code_phase_2',
            name='unique_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
