# Generated by Django 5.1.4 on 2025-12-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_form_participant_unique_code_phase_2_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Participant_Phase_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('institution', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('membership_type', models.CharField(choices=[('student_member', 'IEEE Student Member'), ('member', 'IEEE Member'), ('non_ieee', 'Non-IEEE Member')], max_length=20)),
                ('ieee_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tshirt_size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], max_length=5, null=True)),
                ('payment_method', models.CharField(choices=[('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Not Set', 'Not Set')], default='Not Set', max_length=10)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant Form (Phase 2)',
            },
        ),
    ]
