# Generated by Django 5.1.4 on 2025-12-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_form_participant_phase_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormStatus_Phase02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Form Status (Phase 2)',
            },
        ),
        migrations.RenameModel(
            old_name='EventFormStatus',
            new_name='EventFormStatus_Phase01',
        ),
        migrations.AlterModelOptions(
            name='eventformstatus_phase01',
            options={'verbose_name': 'Event Form Status (Phase 1)'},
        ),
    ]
