# Generated by Django 5.1.4 on 2025-12-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_eventformstatus_phase02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_participant_phase_2',
            name='membership_type',
            field=models.CharField(choices=[('student', 'IEEE Student Member'), ('professional', 'IEEE Member'), ('non_ieee', 'Non-IEEE Member')], max_length=20),
        ),
    ]
