# Generated by Django 5.1.4 on 2025-12-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_form_participant_phase_2_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_participant_phase_2',
            name='is_payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
